setup.py
tacs/TACS.pxd
tacs/TACS.pyx
tacs/constitutive.pxd
tacs/constitutive.pyx
tacs/elements.pxd
tacs/elements.pyx
tacs/functions.pxd
tacs/functions.pyx

Added decoding of compiler flags to UTF-8. Building using Python 3 (on Mac) didn't include the include directories (although they were found in setup.py) because the string comparison was failing for bytes literals. Also moved the c++ language option to the Cython files and removed it from setup.py, as the language option for cythonize is deprecated.

changes for Python 3 compatibility

---

examples/shell/jacobian.cpp
src/elements/shell/TACSDirector.h
src/elements/shell/TACSShellElement.h
src/elements/shell/TACSShellElementDefs.h
src/elements/shell/TACSThermalShellElement.h
tacs/elements.pxd
tacs/elements.pyx
tests/element_tests/shell_tests/test_shell_element.py

The following changes were made:
- simplified the director residual to contain a single director argument for the residual
- added tests for the thermal shell element in tests/element_tests/shell_tests
- fixed adjResProduct code for the quaternion and quadratic rotational parametrizations

Added thermal shell elements to the python interface and added tests

---

tacs/pymeshloader.py

- Adding automatic check in mesh loading procedure for any nodes not belonging to at least one element
- A detailed error message will be printed out if any unattached nodes are found
- This check is run before the TACS assembler is created in order to prevent a segfault occur from occurring

Adding check in meshloader for unattached nodes

---

.github/workflows/unit_tests.yml

- adding openmpi environment variables to workflow that allow for processor oversubscribing and prevent testflo tests from failing due to a lack of mpi slots

Adding fix to slot error for parallel CI tests

---

examples/battery/battery_runaway.py
examples/thermal_plate/analysis.py
src/elements/TACSElement.h
src/elements/TACSElement2D.cpp
src/elements/TACSElement2D.h
src/elements/TACSElement3D.cpp
src/elements/TACSElement3D.h
src/elements/shell/TACSMassElement.cpp
src/elements/shell/TACSMassElement.h
src/elements/shell/TACSMassInertialForce.h
src/elements/shell/TACSRBE2.cpp
src/elements/shell/TACSRBE2.h
src/elements/shell/TACSRBE3.cpp
src/elements/shell/TACSRBE3.h
src/elements/shell/TACSShellElement.h
src/elements/shell/TACSShellPressure.h
src/elements/shell/TACSShellTraction.h
src/elements/shell/TACSSpringElement.cpp
src/elements/shell/TACSSpringElement.h
src/elements/shell/TACSThermalShellElement.h
tacs/TACS.pxd
tacs/TACS.pyx
tacs/pytacs.py

- Added virtual method to get element output types for each element class
- F5 output element type is now inferred from the first element type in the model, rather than based on `varsPerNode` (which was not unique)
- Users no longer have to specify element type in options, unless multiple element types are present in model

Automating output type in pyTACS

---

.github/workflows/unit_tests.yml
Makefile
Makefile.in.info
README.md
docs/source/install.rst
pyproject.toml
setup.py

- Updating setup.py to support traditional pip install procedure
- python interface can now be installed in place using (developer): `pip install -e .`
- python interface can now to site packages (user): `pip install .`
- Addresses #89 
- Adding temporary fix for broken pynastran dependency: nptyping (SteveDoyle2/pyNastran#691)

Modifying setup.py

---

.gitignore
src/TacsComplexStep.h

Since the helper function fabs() has exact same definition in tacs/src/TacsComplexStep.h and paropt/src/ParOptComplexStep.h, the build of TMR interface will fail because it includes both headers that such a redefinition will cause complication error. Here a solution is proposed that uses compiler directive to prevent redefinition.

use include guard to prevent redefinition for fabs()

---

tests/integration_tests/static_analysis_base_test.py

- Some of the integration tests are using a relative tolerance of 1e-8 for the cs sensitivities, which is the same as the default KSM linear solver accuracy
- Decreasing the KSM tolerance to 1e-12, so sensitivities will be more accurate and CI will pass

Fix for failing integration test

---

setup.py

- mphys dependency was previously linked directly to github repo a ("mphys @ git+https://github.com/OpenMDAO/mphys.git"), we can now remove this since a [pypi package](https://pypi.org/project/mphys/) exists for the library
- Removing this will also fix an issue where mphys was always forcibly reinstalled with tacs, even if an existing install for mphys was already present

Removing mphys github repo from setup.py dependency

---

Makefile
pyproject.toml

- This option has officially been deprecated in the newest version of pip and has been a default in recent versions anyways

removing pip in-tree-build flag from makefile

---

pyproject.toml
setup.py

- Also adding minimum version for optional dependency testflo

Making minimum required mpi4py 3.1.0

---

Makefile.in.info
extern/f5totec/Makefile
extern/f5tovtk/Makefile

-lopen-pal seems to be an OpenMPI specific library (doesn't work for MPICH), so I'm moving this flag from the makefile into the Makefile.in.info

Moving lopen-pal flag to makefile.in with the rest of TECIO vars

---

tacs/problems/base.py
tacs/problems/static.py
tacs/problems/transient.py
tacs/pytacs.py
tests/integration_tests/input_files/transient_beam.bdf
tests/integration_tests/test_trans_beam.py

- Transient problems can now be read in and created directly from BDF using 'createTACSProbsFromBDF' method
- 'createTACSProbsFromBDF' method now supports reading:
- StaticProblem
- TransientProblem
- ModalProblem
- Added new problem method to add loads from BDF manually (`addLoadFromBDF`)

Adding transient problem types to BDF parser

---

src/TACSIntegrator.cpp
src/TACSIntegrator.h
tacs/TACS.pxd
tacs/TACS.pyx
tacs/problems/transient.py

-ESDIRK time integration added to TACSIntegrator and python interface
-ESDIRK adjoint not yet implemented
-Extended transientProblem to be used for multidisciplinary coupling
ESDIRK is very similar to the existing DIRK method, with the difference that the first stage is explicit, and the remaining stages are implicit. This slightly changes the integration logic and steps that need to be followed to iterate the time-marching solution. The ESDIRK method implemented includes a 4-stage, 3rd-order accurate scheme, a 6-stage, 4th-order scheme, and an 8-stage, 5th-order accurate scheme. The coefficients for these schemes are taken from [this reference](https://www.sciencedirect.com/science/article/pii/S0168927402001381). These ESDIRK schemes have been used for tightly coupled, high-order time …

ESDIRK time integration

---

.gitignore
Makefile.in.info
docs/source/install.rst
extern/Makefile

Since UFConfig and AMD are no longer available individually, I updated the extern makefile and installation instructions such that they work with the commonly available SuiteSparse tarball.

Update extern installation to use SuiteSparse

---

tacs/problems/base.py
tacs/problems/static.py
tacs/problems/transient.py
tests/integration_tests/pytacs_analysis_base_test.py
tests/integration_tests/test_I_beam_mixed.py
tests/integration_tests/test_beam_bend_coupling.py
tests/integration_tests/test_beam_point_mass.py
tests/integration_tests/test_elast_beam_quadtetra_element_3d.py
tests/integration_tests/test_elast_centrifugal_quadtetra_element_3d.py
tests/integration_tests/test_general_mass_element.py
tests/integration_tests/test_point_mass_element.py
tests/integration_tests/test_rectangle_beam_rotated.py
tests/integration_tests/test_rectangle_beam_tractions.py
tests/integration_tests/test_rigid_body_mass.py
tests/integration_tests/test_shell_cylinder_quad.py
tests/integration_tests/test_shell_hemisphere_mixed.py
tests/integration_tests/test_shell_plate_partitioned.py
tests/integration_tests/test_shell_plate_quad.py
tests/integration_tests/test_shell_plate_rotated.py
tests/integration_tests/test_simple_spring.py
tests/integration_tests/test_thermal_element_2d.py
tests/integration_tests/test_thermal_initial_conditions.py
tests/integration_tests/test_trans_beam.py
tests/integration_tests/test_trans_beam_dirk.py
tests/integration_tests/test_tube_beam.py

- Refactoring pytacs integration tests to simplify test creation
- Reduces number redundant/unnecessary information that had to be defined by users in the past for these tests
- See test [here](https://github.com/timryanb/tacs/blob/test-refactor/tests/integration_tests/test_point_mass_element.py) for example

pyTACS Test refactor

---

examples/battery/battery_runaway.py
tacs/utilities.py

- Tying pytacs info statement printing to "printLevel" option
- Should avoid excessive printing when users have to add loads repeatedly, like for `TransientProblem`

Tying pyTACS verbosity to `printLevel`

---

tests/integration_tests/test_shell_plate_rbe2.py
tests/integration_tests/test_shell_plate_rbe3.py

Some characters in the docstring of a few of the tests lead to warnings like the following showing up:
```
/Users/trbrooks/git/tacs/tests/integration_tests/test_shell_plate_rbe3.py:6: DeprecationWarning: invalid escape sequence \
```
Making the docstring a literal fixes this

Changing test docstring to literal to suppress python string warning

---

.github/workflows/black.yml
.github/workflows/clang-format-check.yml

Currently, the formatting checks (black and clang-format) are setup to run on all pull requests and all pushes, this means that any commits that get pushed to a PR branch have the formatting checks run on them twice (e.g [here](https://github.com/smdogroup/tacs/pull/139/checks))
This PR fixes this by specifying that all PRs but only pushes to the master branch should have the formatting check run on them, which means that the checks will be run once on PRs and then again on the new master branch once a PR is merged. 
I also noticed that the unit testing action is only setup to run on PRs targeting the master branch, is this on-purpose or should we also enable that action for all PRs?

Avoid running format checks twice on PRs

---

.github/workflows/unit_tests.yml

- Should prevent cases with hanging runs

Adding maximum timeout of 30 min for unit tests CI

---

.github/workflows/unit_tests.yml

This should fix the issue where sometimes the CI will cancel the wrong job when quick subsequent commits are made to the same branch
- It appears to work as expected: https://github.com/smdogroup/tacs/actions/runs/3595208513

CI concurrency fix

---

Makefile
Makefile.in.info

- It appears TACS_DEF was only being passed for the complex build
- Also adding define flag for AMD library to `Makefile.in.info`

Adding TACS_DEF to make `real` recipe

---

tacs/TACS.pyx

Fixes issue described in #157  where TACS segfaults if the scipy sparse matrix returned by `getMat` is garbage collected before the rest of the TACS data

Fix reference counting in getMat

---

tacs/pytacs.py

The decorator automatically checks if the assembler is or isn't initialized before the method and raises an error correspondingly
Methods not protected by decorators are safe to call at any time

Adding decorator to protect pytacs pre/postinitialize methods

---

src/elements/shell/TACSRBE2.cpp
src/elements/shell/TACSRBE2.h
src/elements/shell/TACSRBE3.cpp
src/elements/shell/TACSRBE3.h
tacs/elements.pxd
tacs/elements.pyx
tacs/problems/base.py
tacs/problems/modal.py
tacs/problems/static.py
tacs/problems/transient.py
tests/element_tests/shell_tests/test_rbe2.py
tests/element_tests/shell_tests/test_rbe3.py
tests/integration_tests/input_files/rbe_test.bdf
tests/integration_tests/test_shell_plate_rbe2.py
tests/integration_tests/test_shell_plate_rbe2_pytacs.py

The RBE elements use a Lagrange Multiplier formulation to compute their stiffnesses. This approach leads to zeros being present in some diagonals of the stiffness matrix, which causes issues when the preconditioner is factored. To get around this, the elements add a small artificial term to their diagonals. This fixes the PC issue, but adds error to the Jacobian.
This PR:
- Separates out the artificial stiffness from the true Jacobian and only adding it in for the preconditioner refactor step
- Adds options to allow user to set the scaling factors used in the RBE elements through the pytacs problem classes
- Improves the default rel. convergence tolerance of static problems featuring RBE elements from ~1e-7 to ~1e-13

Improving RBE accuracy for static problems

---

src/bpmat/GSEP.cpp
src/bpmat/KSM.cpp
src/bpmat/KSM.h
tacs/TACS.pxd
tacs/TACS.pyx
tacs/problems/static.py

- Adding explicit warning message if linear solver fails in `StaticProblem.solve` method
- This should help users catch issues with models that may be ill-conditioned by design (i.e. missing bcs)

Adding warning for ill-conditioned static problems

---

tacs/problems/base.py
tacs/pytacs.py

- The pyTACS decorators added to methods in #159 inadvertently messed up the dosctrings for some of the methods in the Sphinx docs
- This PR fixes the issue by using the built-in `wraps` decorator to ensure that all docstring metadata is copied correctly for the decorated methods

Fixing pytacs docstrings using wrap method

---

examples/plate/analysis.py
src/TACSAssembler.cpp
tacs/problems/modal.py
tests/integration_tests/test_shell_plate_quad.py

- Our nightly benchmark tests caught a change in the modal analysis results of one of our pytacs [examples](https://github.com/smdogroup/tacs/blob/master/examples/plate/analysis.py) (benchmarks can also be run locally using `$testflo -b .`)
- I narrowed the problem down to this [line](https://github.com/smdogroup/tacs/blob/master/src/TACSAssembler.cpp#L4452) of code in the `assembleMatType` procedure which was causing TACSFrequencyAnalysis to behave differently
- The problem is that `getMatType` isn't an additive procedure (like `addJacobian`) so everytime the auxiliary element contribution is computed, it overwrites the element contribution
- The fix to this was to always split out the auxelem matrix contribution and then scale (rather than conditionally doing so)
- I also added a new …

Fixing issue in AssembleMatType procedure

---

pyproject.toml
setup.py

mpi4py 3.1.0 has a typo in it's python dependencies definition that causes errors during pip install (see [here](https://github.com/mpi4py/mpi4py/releases/tag/3.1.1) and [here](https://github.com/mpi4py/mpi4py/commit/e77486bea7a7520d09cea48cd03a98d583a85f60)). Due to a new [major release](https://pypi.org/project/setuptools/#history) of setuptools (best guess), this just started causing build errors on our docker images (see [here](https://github.com/mdolab/docker/actions/runs/4040746729/jobs/6946677857#step:10:9815))
This PR therefore bumps the minimum required version of mpi4py to 3.1.1 where the error is fixed.
Also includes the OpenMDAO version guard from #174 
Bumping TACS version to 3.2.0

Bump min required mpi4py to 3.1.1

---

tacs/problems/base.py
tacs/problems/modal.py
tacs/problems/static.py
tacs/problems/transient.py
tacs/pymeshloader.py
tacs/pytacs.py
tacs/utilities.py
tests/integration_tests/test_rigid_body_mass.py
tests/integration_tests/test_thermal_initial_conditions.py

Previously, all pyTACS classes had the same boilerplate code in their `__init__` methods for setting up their MPI communicators and options dictionaries. This PR moves that code into the `__init__` method of the `BaseUI` class which is inherited by all pyTACS classes, reducing repeated code.

Add `__init__` method to `BaseUI` for setting up pyTACS options/comm

---

src/bpmat/KSM.cpp
src/bpmat/KSM.h
tacs/TACS.pxd
tacs/TACS.pyx
tests/integration_tests/static_analysis_base_test.py

In my nonlinear solver, I wanted to be able to check the final residual and the number of iterations from each linear solve (e.g to decide whether the preconditioner needs to be updated), this PR adds this functionality for all solvers that inherit from `TACSKsm` 
PR Summary:
- Adds protected `iterCount` and `resNorm` attributes to the abstract `TACSKsm` class, `iterCount` is the total number of iterations taken for the last linear solve and `resNorm` is the residual norm from the end of the last linear solve.
- Adds default constructor to `TACSKsm` that initialises `iterCount` and `resNorm` to 0
- Adds getter methods for `iterCount` and `resNorm` to `TACSKsm` and their python interfaces
- Adds code to update  `iterCount` and `resNorm` to the end of the `solve` methods of the `PCG`, …

Add methods for retreiving number of iterations and residual norm from KSM linear solvers

---

src/elements/shell/TACSBeamElement.h
src/elements/shell/TACSShellElementTransform.h

Adding warning messages for invalid ref axes in Beam/Shell classes.
This adds a check for the ShellRefAxisTransform that makes sure the ref axis isn't perpendicular to the element
and a check for the BeamRefAxisTransform that makes sure the ref axis isn't parallel to the beam axis.

Adding warnings for invalid beam/shell ref axes

---

tests/integration_tests/test_caps_shape_derivatives.py
tests/integration_tests/test_caps_thick_derivatives.py

* Previously both unit tests were assigned the same auto-workdir name with ESP/CAPS called "capsStruct".
* There was a testflo error in which one processor tried to start a caps unittest while the other was running and encountered the capsLock file, crashing the test.
* Solution is to have each CAPS unittest run on separate automatic work directories with names "capsStruct1", "capsStruct2".

Separate problem names/workdir for Caps unittests

---

examples/mg/mg.cpp
examples/spectral/Makefile
examples/spectral/spectral.cpp
extern/f5tovtk/f5tovtk.cpp
src/Makefile
src/TACSSpectralIntegrator.cpp
src/TACSSpectralIntegrator.h
src/bpmat/BCSRMat.cpp
src/bpmat/BCSRMat.h
src/bpmat/KSM.h
src/bpmat/TACSParallelMat.cpp
src/bpmat/TACSParallelMat.h
tacs/TACS.pxd
tacs/TACS.pyx

This code implements a time-spectral approach for integrating the equations of motion in time. This is only for first-order systems in time (such as thermal problems) and could be extended to second-order systems or periodic systems.

Time spectral finite-element implementation

---

src/elements/basis/TACSHexaBasis.cpp
tacs/problems/base.py
tests/integration_tests/input_files/two_hexs.bdf
tests/integration_tests/test_elast_linhexa_pressure_3d.py

Fixing two bugs that lead to pressure loads being applied incorrectly for hexahedral elements

Fixing face inconsistencies in LinearHex element

---

examples/crm/crm_opt.py
src/TACSAssembler.cpp
tacs/TACS.pyx
tacs/problems/base.py
tacs/pytacs.py

- updating crm_opt.py example to work with current tacs/paropt API
- adding `getDesignVarRange` method to pyTACS

Updating crm_opt example to work with current API

---

tacs/TACS.pxd
tacs/TACS.pyx
tacs/pytacs.py

- Not all constitutive dvs are updated on root proc by TACSAssembler when `writeBDF` is called parallel
- This is because TACSAssembler's `setDesignVars` method only updates element objects owned by each processor
- To fix this we directly set variable values to element class in `writeBDF` procedure

Fixing issue with `writeBDF` in parallel

---

tacs/problems/base.py
tacs/problems/modal.py
tacs/problems/static.py
tacs/problems/transient.py
tacs/pymeshloader.py
tacs/pytacs.py
tacs/system.py

Minor updates to pyTACS docstrings. Merge this before PR #206

Minor docstring update

---

docs/source/conf.py
docs/source/examples/Example-Transient_Battery.rst
tacs/constraints/adjacency.py
tacs/constraints/base.py
tacs/constraints/dv.py
tacs/constraints/volume.py
tacs/problems/base.py
tacs/problems/static.py
tacs/problems/transient.py
tacs/pymeshloader.py
tacs/pytacs.py
tacs/system.py

Adding missing docstrings. Cleaning up typos

pyTACS docstring cleanup

---

pyproject.toml

Apparently, Python 3.11 isn't compatible with older versions (<3.1.4) of mpi4py, see [release notes](https://github.com/mpi4py/mpi4py/releases/tag/3.1.4). To fix this we can add a conditional mpi4py version requirement for Python versions >= 3.11

Fixing issue with mpi4py build requirement on Python 3.11

---

tacs/mphys/mphys_tacs.py
tests/integration_tests/test_mphys_struct_plate.py

Adds methods to the `TACSBuilder` class to retrieve the DV bounds and scaling factors that have been defined in the `element_callback`. This makes it easy to define the DV bounds and scales when using TACS through MPhys, e.g
```python
dvs = self.add_subsystem("dvs", om.IndepVarComp(), promotes=["*"])
structDVs = tacs_builder.get_initial_dvs()
dvs.add_output("dv_struct", structDVs)
lb, ub = tacs_builder.get_dv_bounds()
structDVScaling = tacs_builder.get_dv_scalers()
self.add_design_var(
"dv_struct", lower=lb, upper=ub, scaler=structDVScaling
)
```

Add methods to mphys interface for getting DV bounds and scaling factors

---

conda/conda_build_config.yaml
conda/meta.yaml

Python 3.7 EOL is coming up soon ([06/27/23](https://endoflife.date/python)). Removing this dependency from conda build matrix

Removing Python 3.7 from conda build

---

.github/workflows/unit_tests.yml
docs/source/pytacs/buckling.rst
src/constitutive/TACSBladeStiffenedShellConstitutive.cpp
src/constitutive/TACSBladeStiffenedShellConstitutive.h
tacs/constitutive.pxd
tacs/constitutive.pyx
tacs/pytacs.py
tests/constitutive_tests/test_blade_sitffened_shell_constitutive.py

- Adds docstrings for all methods in the `BladeStiffenedShellConstitutive` cython class
- Change default bounds on ply fraction variables in `BladeStiffenedShellConstitutive` from 0.1-0.9 to 0.0-1.0
- Fix bug in DV numbers used in `BladeStiffenedShellConstitutive` unit tests
- Fixes error from a merge commit where `generateBDFCard` was accidentally moved from `CompositeShellConstitutive` to `BladeStiffenedShellConstitutive`
- Some small fixes to docstring issues in `BucklingProblem` and `pyTACS`

`BladeStiffenedShellConstitutive` and documentation improvements

---

pyproject.toml

[Cython 3.0](https://cython.readthedocs.io/en/latest/src/changes.html#unified-release-notes) just came out and seems to break the TACS build (see [here](https://github.com/smdogroup/tacs/actions/runs/5581344219/jobs/10199381683))
We should definitely work on fixing these issues, but for now, this PR updates the build requirements to require a cython version <3.0 so that the build works.

Require cython<3.0

---

.github/workflows/unit_tests.yml
README.md
conda/meta.yaml
docs/source/install.rst

The recently released metis 5.1.1 package on conda forge seems to be causing segfault issues in TACS environments setup through conda (see [here](https://github.com/timryanb/mphys/actions/runs/5622597192/job/15235542766)). 
Pinning CI/conda recipe against older 5.1.0 package to prevent this in future
Also updating broken Metis download link in ReadMe/docs. Closes issue #235

pinning against metis 5.1.0

---

tacs/caps2tacs/aflr_aim.py
tacs/caps2tacs/egads_aim.py
tacs/caps2tacs/tacs_aim.py
tacs/caps2tacs/tacs_model.py

Similar to recent updates in FUNtoFEM, this adds the ability to use dictionaries directly to set aflr4AIM options.

Add dictionary input for setting aflr4AIM options.

---

conda/meta.yaml

- anaconda sometimes pulls old versions of numba which break the install
- Adding version pin for numba to conda recipe

Conda numba build fix

---

tacs/pymeshloader.py

The conversion from global to local nodeIDs in `getLocalNodeIDsForComps` doesn't currently account for the node reordering that TACS does after the mesh is loaded. @timryanb came up with this fix so that it does.

Fix local node ID conversion in `getLocalNodeIDsForComps`

---

tacs/pymeshloader.py

- Adding a necessary ownership check before returning nodes in `getLocalNodeIDsForComps` if run in parallel

Minor fix for when getLocalNodeIDsForComps is called in parallel

---

tacs/caps2tacs/materials.py
tacs/caps2tacs/tacs_aim.py
tacs/caps2tacs/tacs_model.py

* Added thermal properties into caps2tacs
* Added code into ESP/CAPS side to accept the thermal properties from caps2tacs into the tacsAIM
* Added code to F2F to accept the thermal properties into the F2F callback
* note TACS doesn't accept the thermal properties still although maybe I could add the features to accept thermal properties from caps2tacs into the pyTACS callback too (Tim?)
* Added triggers for new structural mesh morphing in ESP/CAPS (@ Marshall Galbraith)

Caps Thermal Properties and Structural Mesh Morphing

---

src/constitutive/TACSBladeStiffenedShellConstitutive.cpp

@bburke38 was running into compilation errors with the latest version of clang due to some print statements involving TacsScalars that weren't written correctly to handle the complex case. This PR should fix those issues.

Fix printing of complex values in blade stiffened shell testing functions

---

tacs/caps2tacs/materials.py
tacs/caps2tacs/tacs_aim.py
tacs/caps2tacs/tacs_model.py

* I've added orthotropic materials to the caps2tacs materials module. 
* Marshall and I added MAT4, MAT5 thermal cards into the tacsAIM which have material IDs that are 100 + the material IDs for the elastic cards (so they are tied together with that property group).
* We can now specify thermal properties for orthotropic materials in caps2tacs => funtofem (namely kappa1 - kappa3, and specific_heat)
* Question: Can we add the material ID = 100 + mid checks into the default pytacs callback too? This would allow us to specify thermal properties from caps2tacs into pure TACS as well. @bburke38 and I think this would be a good idea, but what do you think @timryanb

add orthotropic material properties for use in funtofem+caps2tacs

---

examples/beam/beam_opt.py
tacs/mphys/__init__.py
tacs/mphys/builder.py
tests/integration_tests/test_mphys_struct_buckling.py
tests/integration_tests/test_mphys_struct_plate.py
tests/integration_tests/test_mphys_struct_point_mass_rbe.py
tests/integration_tests/test_mphys_thermal_plate.py

Refactoring MPhys TacsBuilder classes __init__ arguments to be more consistent.
Right now we have a number of inputs that have to be passed in through an options dictionary and some that do not.
The `mesh_file`, for example, is passed in through the options dict, even though it is not optional.
I've broken each of the inputs out and given each their own argument in the init function make things more consistent.
Since this is a breaking change, I still allow for the old method (passing the inputs through an options dict) to work, with a DeprecationWarning raised in this case. I've tentatively set the full deprecation of this feature to take place in version 3.7.0 to give people time to update.

TacsBuilder init refactor

---

tacs/constitutive.pyx

- Since PR #252 , invalid input args being passed to MaterialProperties change the default material type to orthotropic
- This can have unexpected behavior for users who accidentally misspell valid isotropic parameters 
- To make the issue clearer the following changes have been made:
1. Passing an invalid/misspelled argument raises an explicit warning
2. Invalid arguments are ignored when deciding if the properties are orthtropic/isotropic

Adding warning to `MaterialProperties` for invalid keyword args

---

setup.py

Numpy 2.0 is expected to be released around December 2023 (numpy/numpy#24300). 
This will be a breaking update, so we have to make sure that our dependencies have a version upper bound to guard against this.

Adding 2.0 version upperbound for numpy in setup.py

---

.github/workflows/deploy_conda_package.yml

- Splitting runners between real and complex to avoid hitting GH max runtime limit

Splitting CI Deployment Runners

---

examples/caps_wing/7_animate_shape_vars.py
tacs/caps2tacs/__init__.py
tacs/caps2tacs/gif_writer.py
tacs/caps2tacs/materials.py
tacs/caps2tacs/tacs_aim.py
tacs/caps2tacs/tacs_model.py
tacs/caps2tacs/variables.py
tacs/problems/base.py

* New routine `tacs_model.animate_shape_variables` can be used to help make gif files of a range of structural shape variables. 
* No forward/adjoint analyses need to be run as that would slow down the animation process. Instead, a `writeDummySensFile` method is included since the tacsAIM postAnalysis expects function and derivative values before creating a new design.
* These features were successfully tested out on the `simple_naca_wing.csm` geometry in `examples/caps_wing/7_animate_shape_variables.py` (a new run script).
* This is useful in debugging the shape variable design spaces in caps2tacs.

Add ability to animate shape variables to a gif in caps2tacs

---

Makefile.in.info

Change `METIS_LIB` to use `METIS_DIR` instead of `TACS_DIR`, since `METIS_DIR` is defined and points to the user's installation of METIS. This makes it a bit simpler to use METIS installed in places outside of `tacs/extern`.

Change METIS_LIB path in Makefile.in.info

---

docs/source/caps2tacs/main.rst
examples/caps_wing/1_steady_analysis.py
examples/caps_wing/6_animate_shape_vars.py
examples/caps_wing/7_multiproc_post_analysis.py
examples/caps_wing/archive/_parallel_test.py
examples/caps_wing/results/gif_writer.py
examples/caps_wing/results/sizing_and_shape2/images/gif_writer.py
setup.py
tacs/caps2tacs/aflr_aim.py
tacs/caps2tacs/analysis_function.py
tacs/caps2tacs/constraints.py
tacs/caps2tacs/egads_aim.py
tacs/caps2tacs/gif_writer.py
tacs/caps2tacs/loads.py
tacs/caps2tacs/materials.py
tacs/caps2tacs/proc_decorator.py
tacs/caps2tacs/property.py
tacs/caps2tacs/tacs_aim.py
tacs/caps2tacs/tacs_component.py
tacs/caps2tacs/tacs_model.py
tacs/caps2tacs/variables.py
tacs/problems/base.py
tacs/pymeshloader.py
tacs/pytacs.py
tests/integration_tests/test_caps_shape_derivatives.py

*  active_procs list in the `TacsModel.build` arg is used to create parallel instances of tacs_aim and egads_aim objects from pyCAPS or ESP/CAPS packages.
* When shape variables change, the geometry of each parallel tacsAIM is updated - especially the root tacsAIM (active_procs[0]) which is responsible for the bdf/dat file aka structure mesh.
* The primary reason for creating parallel instances of tacsAIM objects is that the `tacs_aim.post_analysis()` call scales with the # of shape variables and is really slowing down the shape optimization of an aerodynamic vehicle geometry in FUNtoFEM. Namely, the tacsAIM.post_analysis takes 26 minutes for the application case in FUNtoFEM with 8 shape variables and a 40 min CFD analysis. We can achieve a theoretical 8x speedup on this example by …

caps2tacs - Parallel Instances of tacsAIMs for huge speed up of post_analysis() for shape optimization

---

src/bpmat/KSM.h
tacs/TACS.pyx
tacs/cpp_headers/TACS.pxd
tacs/pytacs.py

Initialise random number generator in `_checkNonlinearity`

---

tacs/caps2tacs/tacs_model.py

* verbosity flag = 0 useful to suppress print statements
* can speed up runtime (esp. for parallel tacsAIMs which requires a lot more print statements)

Suppress print statements mode in caps2tacs

---

tacs/caps2tacs/tacs_aim.py

Unexpected behavior when DV_dict was None or empty: need to check that it exists before passing it to the AIM.

Fix bug in caps2tacs when DV_dict is None.

---

tacs/caps2tacs/tacs_aim.py
tacs/caps2tacs/tacs_model.py

Allow setting inactive thickness variable's membrane thickness without adding to DV and DVR in caps2tacs.
Also fix bug/typo from `==` to `=` in `tacs_aim.py`.
Corresponds to PR 274 on FUNtoFEM.

Allow setting inactive thickness variables in caps2tacs.

---

tests/integration_tests/openmdao_analysis_base_test.py
tests/integration_tests/pytacs_analysis_base_test.py

Addresses #301. Should fix intermitent test failures we've been seeing on CI recently

Adding random generator seed to all pytacs/mphys tests

---

examples/caps_wing/10_blade_stiffened.py
examples/caps_wing/_blade_callback.py
examples/caps_wing/simple_naca_wing.csm
tacs/caps2tacs/aflr_aim.py
tacs/caps2tacs/analysis_function.py
tacs/caps2tacs/constraints.py
tacs/caps2tacs/gif_writer.py
tacs/caps2tacs/loads.py
tacs/caps2tacs/materials.py
tacs/caps2tacs/property.py
tacs/caps2tacs/tacs_component.py
tacs/caps2tacs/tacs_model.py
tacs/caps2tacs/variables.py

* Made a change in the tacsAIM of ESP/CAPS (what caps2tacs is built off of) that writes out TACS Component labels. This way the user should be able to make their own element callbacks now in TACS using BDF/DAT files created from ESP/CAPS.
* Accepts element callbacks in the `TacsModel` clas
* Adapts Alasdair Gray's blade stiffener examples in examples/mach_tutorial_wing since we are using this for an aeroelastic benchmark case in FUNtoFEM.

Accept Element Callbacks in caps2tacs + Adapt Mach Wing Example

---

tacs/problems/static.py

I noticed that the Jacobian matrix gets updated every time the static problem is called (even if the design vars/nodes haven't changed). This leads to the PC being refactored every time which significantly slows down the code for linear analysis. To fix this I add a missing statement at the end of the Jacobian update procedure that sets the` _jacobianUpdateRequired` flag to `False`. This speeds up my MPhys run cases by a factor ~5x in the forward and reverse solve procdures

Fixing bug with Jacobian update that slowed down `StaticProblem` solve procedure

---

setup.py

- Creating new bug fix release due to #309 being a significant speedup in the MPhys wrapper
- This will also include bugfix #304  
- Merge after #309

Bumping to version 3.7.1

---

.github/workflows/deploy_conda_package.yml

Github recently changed `macos-latest` runner to an M1 build. Updating CI deploy workflow to work with new changes

Conda deploy fix

---

src/elements/TACSPressure2D.cpp
tests/integration_tests/test_thermoelast_linquad_element_2d.py

Compiling TACS with the new intel `icpx` compiler surfaced some new errors, one in `element_tests/test_pressure_2d` and another in `integration_tests/test_thermoelast_linquad_element_2d.py`.
Changes made:
- Fix memset of incorrect size in `TACSPressure2D`
- Remove duplicated residual calculation code from the `addJacobian` method of `TACSPressure2D`
- Slightly changed the FD step size used in the `test_thermoelast_linquad_element_2d` to give more accurate FD derivatives
Example of TACSPressure2d issue:
Before fix:
```
Testing residual consistency of addJacobian method for element TACSPressure2D.
Max Err: 5.2003e+00 in component 0.
Max REr: 1.7875e+00 in component 0.
The difference between addResidual and addJacobian residuals is
Val[   ]                  Analytic               Approximate …
```

Fixing errors caused by `icpx` compilation

---

tests/integration_tests/test_trans_beam.py

Similar to #316 , we are seeing some hard to reproduce test failures in the xpt sens test in `test_trans_beam`. I can't be 100% sure that this step size change fixes the error but it does reduce the largest relative error by roughly 2 orders of magnitude:
Before:
```
Testing sinusoid_compliance xpt sens:
analytic: 12.398071807030135
FD: 12.397875767788946
diff: 0.00019603924118882787
rel diff: 1.581207499360238e-05
```
After:
```
Testing sinusoid_compliance xpt sens:
analytic: 12.398070774567254
FD: 12.398069415553437
diff: 1.3590138170371802e-06
rel diff: 1.0961494265906186e-07
```

Update test_trans_beam FD step size

---

src/constitutive/TACSBladeStiffenedShellConstitutive.cpp
src/constitutive/TACSBladeStiffenedShellConstitutive.h
src/constitutive/TACSConstitutive.h
src/elements/TACSElementTypes.cpp
src/elements/shell/TACSBeamElement.h
src/elements/shell/TACSShellElement.h
src/elements/shell/TACSThermalShellElement.h

- shell/beam f5 files will now have 5 unique failure fields ("failure0", "failure1", etc.)
- This is handled by new `evalFailureFieldValue` method in `TACSConstitutive` class
- This allows for multiple failure mode contours to be visualized in post-processing (as was requested in PR's #319 and #311)
- "failure0" defaults to whatever is given by `evalFailure` method (same value we've previously been writing out) and the rest default to 0 (This can be overridden at the sub-class level)
- Closes #320

Adding capability to write multiple failure values to f5 file

---

conda/meta.yaml
setup.py

[mpi4py 4.0.0](https://pypi.org/project/mpi4py/) was officially released on pip recently and is breaking the tacs python install. I've added a version upper bound to prevent this in the future.

Adding version upperbound for mpi4py

---

docs/source/install.rst

Getting the ball rolling on the docs section covering the TACS installation process on common HPC systems. Feel free to change the content I added or where in the docs it goes.

Add docs section on HPC installation

---

.github/dependabot.yaml

A number of the pre-existing github action steps we use are quite out of date, which can cause CI jobs to fail , e.g in #329 we had to update the `upload_artifacts` action because it was killing our unit tests job, and we are currently getting warnings on our linting job because the version of the `checkout` action we use is soon to be deprecated.
To save us the effort of manually keeping them up to date, we can use GitHub's dependabot. The config I have in this PR will have the dependabot run once a month and open a PR to update any of the actions we're using that are out of date. For an example, see https://github.com/A-CGray/FEMpy/pull/68.
Someone with the relevant permissions will also have to enable dependabot in the repo settings (below are the settings I have on one of my …

Use dependabot to keep github actions up to date

---

examples/annulus/annulus.cpp
examples/annulus/generate_bdf.py
src/io/TACSMeshLoader.cpp
src/io/TACSMeshLoader.h

Adds the ability for TACSMeshReader to read in higher order quad elements. I also updated the annulus example to work with these element types, results below.
Unfortunately, because CQUAD16 and CQUAD25 are not NASTRAN element types, the pymeshloader cannot read these elements.
Additionally, I was running into some multiple definition errors caused by a couple of variables that are defined in the TACSMeshLoader header file when compiling code that links to both TACS and an object file that uses TACSMeshLoader, for example:
TACSHelpers.h:
```cpp
#pragma once
#include "TACSMeshLoader.h"
void createTACSAssembler(const char *filename, TACSAssembler *&assembler);
```
TACSHelpers.cpp:
```cpp
#include "TACSHelpers.h"
void createTACSAssembler(const char *filename, TACSAssembler *&assembler) {
// …
```

Add TACSMeshReader support for 16 and 25 node quad elements

---

conda/meta.yaml
pyproject.toml
setup.py

Python 3.12+ seems to be incompatible with older versions of mpi4py. In order to fix this we'll need to bump up minimum mpi4py version to 3.1.5.

Making mpi4py 3.1.5 new minimum version for build

---

.github/workflows/deploy_conda_package.yml
conda/build.sh
setup.py

This version bump updates TACS MPhys wrapper to support MPhys 2.0. 
This will be a backwards-incompatible update for any MPhys users.
To be merged in after PR #315 and #337

Version bump 3.8.0

---

setup.py

Deploying bugfix version to fix issue with OpenMDAO `check_partials` [change](https://github.com/OpenMDAO/OpenMDAO/pull/3424) which breaks MPhys wrapper.

3.8.1 bug fix version bump

---

tacs/mphys/builder.py
tacs/mphys/coupling.py
tacs/mphys/functions.py
tacs/mphys/postcoupling.py

Apparently I missed a few `check_partials` attributes in PR #348

Fixing remaining check_partials attributes in mphys wrappers

---

tests/integration_tests/openmdao_analysis_base_test.py

This Pr should fix issues that will arise when OpenMDAO [PR #3465](https://github.com/OpenMDAO/OpenMDAO/pull/3465) is merged in

updating openmdao tests to work with upcoming version release

---

.github/workflows/black.yml

There seems to be a minor issue in black 24.1.0 that was causing most of our python files to be ignored in the CI check (see [here](https://github.com/smdogroup/tacs/actions/runs/13633865001)). bumping the version up to 24.10.0 which seems to fix issue.

black CI fix

---

.github/workflows/unit_tests.yml
examples/cylinder/cylinder_verify.cpp
examples/four_bar_mechanism/four_bar_mechanism.cpp
examples/stiffened_panel/skewed_plate.cpp
examples/stiffened_panel/stiffened_panel.cpp
src/TACSBuckling.cpp
src/TACSContinuation.cpp
src/TACSIntegrator.cpp
src/TACSMg.cpp
src/bpmat/GSEP.cpp
src/bpmat/JacobiDavidson.cpp
src/bpmat/KSM.cpp
src/constitutive/TACSGPBladeStiffenedShellConstitutive.h
src/constitutive/TACSPanelAnalysis.cpp
src/elements/dynamics/MITC3.cpp
src/elements/dynamics/MITC9.cpp
src/elements/dynamics/TACSRigidBody.cpp
src/io/TACSMeshLoader.cpp
src/io/TACSToFH5.cpp

Minor edit to replace all `sprintf` functions with safer `snprintf` in C++ code.

Clean up compiler warnings

---

setup.py

The TACS MPhys wrapper uses the `always_opt` OpenMDAO component option, which was only [added](https://github.com/OpenMDAO/OpenMDAO/commit/fec0bc3a075ada90a0e5072be7730ca61c8c4283) to OpenMDAO in v3.27

Update minimum supported OpenMDAO version

---

pyproject.toml
setup.py
tacs/mphys/functions.py

I've tested numpy 2.0 and it works with pyNastran 1.5.0-dev, so I'm removing the version upperbound from the tacs requirements

removing numpy 2.0 upperbound

---

extern/f5totec/f5totec.cpp

Fixing bug in f5totec where array was being incorrectly indexed by component number rather than by basic element number.  Could cause issues with post-processing mixed element f5 models

fixing indexing bug in f5totec

---

tacs/problems/buckling.py
tacs/problems/static.py
tests/integration_tests/test_shell_cylinder_quad.py
tests/integration_tests/test_shell_plate_buckling_axial.py

There's currently a bug in the `setOption` method that causes all saved loads and eval functions to be deleted if it is called after the loads and functions are added to the problem. This PR resolves the issue by splitting the variable object initialization from the solver initialization, so the solver can be updated after an option change with out zeroing out previously populated tacs objects and vectors

Fixing bug with `StaticProblem`/`BucklingProblem` `setOption` method

---

Makefile.in.info
docs/source/install.rst
extern/Makefile

Had some issues building TACS this morning because my computer had updated to GCC 15 and CMake 4:
- CMake 4 cannot configure projects that ask for CMake<3.5, METIS asks for 2.8, I added some code to the extern Makefile that will add the necessary flag to the METIS config command if you have CMake>=4
- Older versions of `SuiteSparse_config.h` include `omp.h` inside an `extern "C"` block, which tells the compiler to treat everything inside it as C code, not C++`. In GCC, `omp.h` now includes C++ templates so cannot be treated as C code. Updating to the latest release of SuiteSparse (7.10.3) fixed this. I updated the version mentioned in the docs and in the Makefile.in template

Some fixes for installing extern packages with latest CMake and GCC versions
