smdogroup/tacs

src/TACSAssembler.cpp, src/constitutive/Makefile, src/constitutive/bladeFSDTStiffness.cpp, src/constitutive/bladeFSDTStiffness.h, tacs/TACS.pxd, tacs/TACS.pyx, tacs/constitutive.pxd, tacs/constitutive.pyx, tacs/elements.pyx, tacs/functions.pyx
This PR addresses:
- add bladeFSDT class
- KSFailure interface:
- setLoadFactor function added
- optional argument added in constructor such that the function can be used for buckling
- getValues member function bvec bug fix
- getComponentNum added to element interface
=> Add bladeFSDT element, bug fix in getValues BVec, KSFailure interface updated, Element interface updated

examples/crm/Makefile, examples/crm/crm.cpp, examples/crm/crm_frequency.cpp, examples/shell/jacobian.cpp, examples/stiffened_panel/Makefile, examples/stiffened_panel/stiffened_panel.cpp, src/constitutive/TACSIsoShellConstitutive.cpp, src/constitutive/TACSIsoShellConstitutive.h, src/constitutive/TACSMaterialProperties.h, src/elements/TACSElement.cpp, src/elements/shell/TACSShellElement.h, src/elements/shell/TACSShellElementDefs.h, src/elements/shell/TACSShellElementModel.h, src/elements/shell/TACSShellInplaneElementModel.h, src/elements/shell/TACSThermalShellElement.h, src/io/TACSMeshLoader.cpp
- More efficient implementation of the shell element model functions and new implementation of the in-plane element models
- Updated and tested CRM example problems
- Fixed sensitivities in TACSIsoShellConstitutive
- Fixed sensitivities in addPointQuantitySVSens/DVSens
=> Updates to the nonlinear element expressions and integrated sensitivity tests

README.md
Fixed doi link for references 3 & 4
=> Changing the reference links

tests/constitutive_tests/test_composite_shell_constitutive.py, tests/constitutive_tests/test_iso_shell_constitutive.py, tests/constitutive_tests/test_plane_stress_constitutive.py, tests/constitutive_tests/test_solid_constitutive.py
Adding seed for random number generators in constitutive tests to get consistent behavior
=> Adding random number seed to constitutive tests

extern/f5totec/Makefile, extern/f5totec/f5totec.cpp, tacs/pytacs.py
- f5totec should now work with all f5 files
- tecplot can now be used to visualize tacs output files in addition to paraview
=> Fixing f5totec

examples/thermal_plate/analysis.py, tacs/problems/modal.py, tacs/problems/static.py, tacs/problems/transient.py, tacs/utilities.py
- pytacs problems should now update solver options when users call `setOption` method after the problem is created
- added a method for printing out all current options for all pytacs class types
=> Improving pytacs options handling

.github/workflows/unit_tests.yml, docs/source/pytacs/pytacs_module.rst
- github-pages should now be updated automatically on push to master
- Deploy will not trigger for pull requests, only once it's accepted and merged
=> Adding deploy step for docs

.github/workflows/unit_tests.yml
- Breaking workflow down into logical steps
- Adding option to run workflow in interactive debug mode
=> Adding refined workflow procedures

tacs/elements.pxd, tacs/elements.pyx, tests/element_tests/shell_tests/test_shell_element.py
* Wrap nonlinear elements (Quad4,9,16, Tri) and Mod Rot/Quaternion elements
* Incorporated testing for nonlinear elements ONLY
=> Wrap nonlinear elements

examples/rbe3/analysis.py, tacs/problems/base.py, tacs/problems/modal.py, tacs/problems/static.py, tacs/problems/transient.py, tacs/pymeshloader.py, tacs/pytacs.py, tacs/utilities.py
- Cleaning up a lot of typos in docstrings and comments
- Cleaning up code formatting
- Some variable reorganization within classes
- Cleaning up unused imports
=> Minor reformat of pyTACS

src/TACSAssembler.cpp
Put final step of addSVsens in TACSAssembler.cpp in a NULL check.
=> extra NULL check in SVsens

.github/workflows/unit_tests.yml, Makefile, README.md, docs/source/install.rst, setup.py
- Adding mphys source url 
- All dependencies should install through pip call now
=> Minor setup mod

examples/beam/benchmark/benchmark_beam_opt.py, examples/beam/ibeam_example.py, tacs/elements.pyx
- minor change that fixes problem on openmdao benchmark runner
- minor docstring fix
=> minor fixes

src/elements/shell/TACSBeamInertialForce.h, src/elements/shell/TACSBeamTraction.h, src/elements/shell/TACSShellInertialForce.h, tests/integration_tests/input_files/beam_model_skewed.bdf, tests/integration_tests/test_rectangle_beam_rotated.py
=> Fixing small bug with element Jacobian for beam traction classes

tacs/problems/transient.py
- Just had one suggested modification to last PR #132 
- Ran the API change by @bradenfrigoletto24, and he's alright w/ the change
=> Changing `solveTimeInstance` method to `iterate` to match `TACSIntegrator` API

tacs/pytacs.py
- Fixing case where pytacs error would quote the wrong number of found elements if only 1 element is returned in elemCallBack
=> Making pytacs missing error message clearer

examples/battery/benchmark/benchmark_battery_runaway.py, tacs/pymeshloader.py
Also, adding battery example to benchmarks
=> Minor refactor to getConnectivityForComp for significant speedup

examples/crm/crm.py, src/io/TACSToFH5.cpp, tests/integration_tests/pytacs_analysis_base_test.py
- Leads to segfault if AuxElems were never set in assembler when f5writer is called w/  `OUTPUT_LOADS` flag
- Adding f5 file write test to pytacs integration tests to catch issue in future
=> Minor fix for if auxelems is initially NULL in TACSToFH5

docs/source/install.rst
Adding instructions explaining install options for Windows users
=> Adding Windows instructions to docs

setup.py
=> Version bump to 3.2.1

docs/source/pytacs/constraints.rst, docs/source/pytacs/panel_length.rst, tacs/constraints/panel_length.py, tacs/constraints/volume.py, tacs/pytacs.py
- Minor modification of docstrings for better sphinx formatting
=> Adding PanelLengthConstraint class to docs

tacs/constitutive.pyx
=> Adding density to getMaterialProperties method

examples/annulus/analysis.py, tacs/pymeshloader.py, tacs/pytacs.py, tests/integration_tests/test_shell_annulus_from_pynastran.py
=> Allowing user to Initialize pyTACS from pynastran BDF object

docs/source/caps2tacs/main.rst, setup.py, tacs/caps2tacs/gif_writer.py, tacs/caps2tacs/tacs_model.py
* Correct caps2tacs documentations typos and formatting issues
* Optional dependency with funtofem to animate shape changes for full vehicle models in ESP/CAPS, TACS, and FUNtoFEM using FUNtoFEM shape variables
=> Corrections to Caps2tacs docs and support for funtofem shape variable animations

.github/workflows/unit_tests.yml
Fix for failing tests now that openmdao 3.31.0 breaks mphys
=> temporary fix for mphys break

src/constitutive/TACSBladeStiffenedShellConstitutive.h, tacs/constitutive.pyx
These commits should have been included in #319 but I missed them.
=> Missing commit from blade-stiffened shell improvements PR

.github/workflows/unit_tests.yml, tacs/mphys/buckling.py, tacs/mphys/solver.py
The following [PR](https://github.com/OpenMDAO/OpenMDAO/pull/3424) in OpenMDAO will add a `check_partials` method to all OpenMDAO components. I've refactored the already existing `check_partials` flag in some mphys components in order to prevent a conflict.
=> renaming `check_partials` attribute in mphys components

docs/source/examples/Example-Plate.rst, docs/source/index.rst, docs/source/postprocessing.rst, docs/source/troubleshooting.rst
- Introduced a new section on postprocessing capabilities and troubleshooting in the documentation.
- Added details on creating and converting f5 files, including output flags and visualization tips.
- Updated the index to include the new postprocessing section.
=> Add postprocessing documentation for TACS solutions
